// Droid platform routes
use crate::state::AppState;
use axum::{
    Router,
    routing::{delete, get, post, put},
};

pub fn routes() -> Router<AppState> {
    Router::new()
        // MCP routes
        .route(
            "/droid/mcp",
            get(crate::api::handlers::platforms::droid::list_droid_mcp_servers),
        )
        .route(
            "/droid/mcp",
            post(crate::api::handlers::platforms::droid::add_droid_mcp_server),
        )
        .route(
            "/droid/mcp/{name}",
            put(crate::api::handlers::platforms::droid::update_droid_mcp_server),
        )
        .route(
            "/droid/mcp/{name}",
            delete(crate::api::handlers::platforms::droid::delete_droid_mcp_server),
        )
        // Custom Models routes
        .route(
            "/droid/models",
            get(crate::api::handlers::platforms::droid::list_droid_custom_models),
        )
        .route(
            "/droid/models",
            post(crate::api::handlers::platforms::droid::add_droid_custom_model),
        )
        .route(
            "/droid/models/{model_id}",
            put(crate::api::handlers::platforms::droid::update_droid_custom_model),
        )
        .route(
            "/droid/models/{model_id}",
            delete(crate::api::handlers::platforms::droid::delete_droid_custom_model),
        )
        // Profiles routes
        .route(
            "/droid/profiles",
            get(crate::api::handlers::platforms::droid::list_droid_profiles),
        )
        .route(
            "/droid/profiles",
            post(crate::api::handlers::platforms::droid::add_droid_profile),
        )
        .route(
            "/droid/profiles/{name}",
            put(crate::api::handlers::platforms::droid::update_droid_profile),
        )
        .route(
            "/droid/profiles/{name}",
            delete(crate::api::handlers::platforms::droid::delete_droid_profile),
        )
        .route(
            "/droid/profiles/{name}/switch",
            post(crate::api::handlers::platforms::droid::switch_droid_profile),
        )
        // Config routes
        .route(
            "/droid/config",
            get(crate::api::handlers::platforms::droid::get_droid_config),
        )
        .route(
            "/droid/config",
            put(crate::api::handlers::platforms::droid::update_droid_config),
        )
        // Droids (Subagents) routes
        .route(
            "/droid/droids",
            get(crate::api::handlers::platforms::droid::list_droids),
        )
        .route(
            "/droid/droids",
            post(crate::api::handlers::platforms::droid::create_droid),
        )
        .route(
            "/droid/droids/{name}",
            get(crate::api::handlers::platforms::droid::get_droid),
        )
        .route(
            "/droid/droids/{name}",
            put(crate::api::handlers::platforms::droid::update_droid),
        )
        .route(
            "/droid/droids/{name}",
            delete(crate::api::handlers::platforms::droid::delete_droid),
        )
        // Agents routes
        .route(
            "/droid/agents",
            get(crate::api::handlers::platforms::droid::list_droid_agents),
        )
        .route(
            "/droid/agents",
            post(crate::api::handlers::platforms::droid::add_droid_agent),
        )
        .route(
            "/droid/agents/{name}",
            get(crate::api::handlers::platforms::droid::get_droid_agent),
        )
        .route(
            "/droid/agents/{name}",
            put(crate::api::handlers::platforms::droid::update_droid_agent),
        )
        .route(
            "/droid/agents/{name}",
            delete(crate::api::handlers::platforms::droid::delete_droid_agent),
        )
        // Slash Commands routes
        .route(
            "/droid/slash-commands",
            get(crate::api::handlers::platforms::droid::list_droid_slash_commands),
        )
        .route(
            "/droid/slash-commands",
            post(crate::api::handlers::platforms::droid::add_droid_slash_command),
        )
        .route(
            "/droid/slash-commands/{name}",
            put(crate::api::handlers::platforms::droid::update_droid_slash_command),
        )
        .route(
            "/droid/slash-commands/{name}",
            delete(crate::api::handlers::platforms::droid::delete_droid_slash_command),
        )
        // Plugins routes
        .route(
            "/droid/plugins",
            get(crate::api::handlers::platforms::droid::list_droid_plugins),
        )
        .route(
            "/droid/plugins",
            post(crate::api::handlers::platforms::droid::add_droid_plugin),
        )
        .route(
            "/droid/plugins/{id}",
            put(crate::api::handlers::platforms::droid::update_droid_plugin),
        )
        .route(
            "/droid/plugins/{id}",
            delete(crate::api::handlers::platforms::droid::delete_droid_plugin),
        )
}
