use axum::{
    Router,
    routing::{delete, get, post, put},
};

pub fn routes() -> Router {
    Router::new()
        .route(
            "/iflow/mcp",
            get(crate::api::handlers::platforms::iflow::list_iflow_mcp_servers),
        )
        .route(
            "/iflow/mcp",
            post(crate::api::handlers::platforms::iflow::add_iflow_mcp_server),
        )
        .route(
            "/iflow/mcp/{name}",
            put(crate::api::handlers::platforms::iflow::update_iflow_mcp_server),
        )
        .route(
            "/iflow/mcp/{name}",
            delete(crate::api::handlers::platforms::iflow::delete_iflow_mcp_server),
        )
        .route(
            "/iflow/agents",
            get(crate::api::handlers::platforms::iflow::list_iflow_agents),
        )
        .route(
            "/iflow/agents",
            post(crate::api::handlers::platforms::iflow::add_iflow_agent),
        )
        .route(
            "/iflow/agents/{name}",
            put(crate::api::handlers::platforms::iflow::update_iflow_agent),
        )
        .route(
            "/iflow/agents/{name}",
            delete(crate::api::handlers::platforms::iflow::delete_iflow_agent),
        )
        .route(
            "/iflow/agents/{name}/toggle",
            put(crate::api::handlers::platforms::iflow::toggle_iflow_agent),
        )
        .route(
            "/iflow/slash-commands",
            get(crate::api::handlers::platforms::iflow::list_iflow_slash_commands),
        )
        .route(
            "/iflow/slash-commands",
            post(crate::api::handlers::platforms::iflow::add_iflow_slash_command),
        )
        .route(
            "/iflow/slash-commands/{name}",
            put(crate::api::handlers::platforms::iflow::update_iflow_slash_command),
        )
        .route(
            "/iflow/slash-commands/{name}",
            delete(crate::api::handlers::platforms::iflow::delete_iflow_slash_command),
        )
        .route(
            "/iflow/slash-commands/{name}/toggle",
            put(crate::api::handlers::platforms::iflow::toggle_iflow_slash_command),
        )
        .route(
            "/iflow/plugins",
            get(crate::api::handlers::platforms::iflow::list_iflow_plugins),
        )
        .route(
            "/iflow/plugins",
            post(crate::api::handlers::platforms::iflow::add_iflow_plugin),
        )
        .route(
            "/iflow/plugins/{id}",
            put(crate::api::handlers::platforms::iflow::update_iflow_plugin),
        )
        .route(
            "/iflow/plugins/{id}",
            delete(crate::api::handlers::platforms::iflow::delete_iflow_plugin),
        )
        .route(
            "/iflow/plugins/{id}/toggle",
            put(crate::api::handlers::platforms::iflow::toggle_iflow_plugin),
        )
}
