// Claude Code 预设供应商数据
// 数据源：cc-switch claudeProviderPresets.ts

import type { PlatformPresets } from '@/types/providerPresets'

export const claudePresets: PlatformPresets = {
  platform: 'claude',
  categories: [
    { id: 'official', label: '官方直连', labelEn: 'Official' },
    { id: 'cn_official', label: '国内官方模型', labelEn: 'CN Official Models' },
    { id: 'aggregator', label: '聚合/中转', labelEn: 'Aggregator' },
    { id: 'third_party', label: '第三方服务', labelEn: 'Third Party' },
  ],
  presets: [
    // ═══════════════════ official ═══════════════════
    {
      id: 'claude-official',
      name: 'Claude Official',
      category: 'official',
      websiteUrl: 'https://www.anthropic.com/claude-code',
      base_url: '',
      provider: 'Anthropic',
      provider_type: 'official_relay',
      description: 'Anthropic 官方直连',
    },

    // ═══════════════════ cn_official ═══════════════════
    {
      id: 'deepseek',
      name: 'DeepSeek',
      category: 'cn_official',
      websiteUrl: 'https://platform.deepseek.com',
      base_url: 'https://api.deepseek.com/anthropic',
      model: 'DeepSeek-V3.2',
      small_fast_model: 'DeepSeek-V3.2',
      provider: 'DeepSeek',
      provider_type: 'third_party_model',
    },
    {
      id: 'zhipu-glm',
      name: 'Zhipu GLM',
      category: 'cn_official',
      websiteUrl: 'https://z.ai',
      apiKeyUrl: 'https://z.ai/subscribe?ic=8JVLJQFSKB',
      base_url: 'https://api.z.ai/api/anthropic',
      model: 'glm-5.2[1m]',
      small_fast_model: 'glm-4.7',
      claude_code_auto_compact_window: '1000000',
      api_timeout_ms: '3000000',
      claude_code_disable_nonessential_traffic: '1',
      provider: 'Zhipu',
      provider_type: 'third_party_model',
    },
    {
      id: 'zai-glm',
      name: 'Z.ai GLM',
      category: 'cn_official',
      websiteUrl: 'https://z.ai',
      apiKeyUrl: 'https://z.ai/subscribe?ic=8JVLJQFSKB',
      base_url: 'https://api.z.ai/api/anthropic',
      model: 'glm-5.2[1m]',
      small_fast_model: 'glm-4.7',
      claude_code_auto_compact_window: '1000000',
      api_timeout_ms: '3000000',
      claude_code_disable_nonessential_traffic: '1',
      provider: 'Z.ai',
      provider_type: 'third_party_model',
    },
    {
      id: 'bailian',
      name: 'Bailian',
      category: 'cn_official',
      websiteUrl: 'https://bailian.console.aliyun.com',
      base_url: 'https://dashscope.aliyuncs.com/apps/anthropic',
      provider: 'Alibaba Cloud',
      provider_type: 'third_party_model',
    },
    {
      id: 'bailian-coding',
      name: 'Bailian For Coding',
      category: 'cn_official',
      websiteUrl: 'https://bailian.console.aliyun.com',
      base_url: 'https://coding.dashscope.aliyuncs.com/apps/anthropic',
      provider: 'Alibaba Cloud',
      provider_type: 'third_party_model',
    },
    {
      id: 'kimi',
      name: 'Kimi',
      category: 'cn_official',
      websiteUrl: 'https://platform.moonshot.cn/console',
      base_url: 'https://api.moonshot.cn/anthropic',
      model: 'kimi-k2.5',
      small_fast_model: 'kimi-k2.5',
      provider: 'Moonshot',
      provider_type: 'third_party_model',
    },
    {
      id: 'kimi-coding',
      name: 'Kimi For Coding',
      category: 'cn_official',
      websiteUrl: 'https://www.kimi.com/coding/docs/',
      base_url: 'https://api.kimi.com/coding/',
      provider: 'Moonshot',
      provider_type: 'third_party_model',
    },
    {
      id: 'stepfun',
      name: 'StepFun',
      category: 'cn_official',
      websiteUrl: 'https://platform.stepfun.ai',
      apiKeyUrl: 'https://platform.stepfun.ai/interface-key',
      base_url: 'https://api.stepfun.ai/v1',
      model: 'step-3.5-flash',
      small_fast_model: 'step-3.5-flash',
      provider: 'StepFun',
      provider_type: 'third_party_model',
    },
    {
      id: 'longcat',
      name: 'Longcat',
      category: 'cn_official',
      websiteUrl: 'https://longcat.chat/platform',
      apiKeyUrl: 'https://longcat.chat/platform/api_keys',
      base_url: 'https://api.longcat.chat/anthropic',
      model: 'LongCat-Flash-Chat',
      small_fast_model: 'LongCat-Flash-Chat',
      provider: 'Longcat',
      provider_type: 'third_party_model',
    },
    {
      id: 'minimax',
      name: 'MiniMax',
      category: 'cn_official',
      websiteUrl: 'https://platform.minimaxi.com',
      apiKeyUrl: 'https://platform.minimaxi.com/subscribe/coding-plan',
      base_url: 'https://api.minimaxi.com/anthropic',
      model: 'MiniMax-M2.5',
      small_fast_model: 'MiniMax-M2.5',
      provider: 'MiniMax',
      provider_type: 'third_party_model',
      isPartner: true,
    },
    {
      id: 'minimax-en',
      name: 'MiniMax (EN)',
      category: 'cn_official',
      websiteUrl: 'https://platform.minimax.io',
      apiKeyUrl: 'https://platform.minimax.io/subscribe/coding-plan',
      base_url: 'https://api.minimax.io/anthropic',
      model: 'MiniMax-M2.5',
      small_fast_model: 'MiniMax-M2.5',
      provider: 'MiniMax',
      provider_type: 'third_party_model',
      isPartner: true,
    },
    {
      id: 'doubao-seed',
      name: 'DouBaoSeed',
      category: 'cn_official',
      websiteUrl: 'https://www.volcengine.com/product/doubao',
      apiKeyUrl: 'https://www.volcengine.com/product/doubao',
      base_url: 'https://ark.cn-beijing.volces.com/api/coding',
      model: 'doubao-seed-2-0-code-preview-latest',
      small_fast_model: 'doubao-seed-2-0-code-preview-latest',
      provider: 'ByteDance',
      provider_type: 'third_party_model',
    },
    {
      id: 'bailing',
      name: 'BaiLing',
      category: 'cn_official',
      websiteUrl: 'https://alipaytbox.yuque.com/sxs0ba/ling/get_started',
      base_url: 'https://api.tbox.cn/api/anthropic',
      model: 'Ling-2.5-1T',
      small_fast_model: 'Ling-2.5-1T',
      provider: 'BaiLing',
      provider_type: 'third_party_model',
    },
    {
      id: 'xiaomi-mimo',
      name: 'Xiaomi MiMo',
      category: 'cn_official',
      websiteUrl: 'https://platform.xiaomimimo.com',
      apiKeyUrl: 'https://platform.xiaomimimo.com/#/console/api-keys',
      base_url: 'https://api.xiaomimimo.com/anthropic',
      model: 'mimo-v2-flash',
      small_fast_model: 'mimo-v2-flash',
      provider: 'Xiaomi',
      provider_type: 'third_party_model',
    },

    // ═══════════════════ aggregator ═══════════════════
    {
      id: 'modelscope',
      name: 'ModelScope',
      category: 'aggregator',
      websiteUrl: 'https://modelscope.cn',
      base_url: 'https://api-inference.modelscope.cn',
      model: 'ZhipuAI/GLM-5',
      small_fast_model: 'ZhipuAI/GLM-5',
      provider: 'ModelScope',
    },
    {
      id: 'aihubmix',
      name: 'AiHubMix',
      category: 'aggregator',
      websiteUrl: 'https://aihubmix.com',
      apiKeyUrl: 'https://aihubmix.com',
      base_url: 'https://aihubmix.com',
      provider: 'AiHubMix',
    },
    {
      id: 'siliconflow',
      name: 'SiliconFlow',
      category: 'aggregator',
      websiteUrl: 'https://siliconflow.cn',
      apiKeyUrl: 'https://cloud.siliconflow.cn/i/drGuwc9k',
      base_url: 'https://api.siliconflow.cn',
      model: 'Pro/MiniMaxAI/MiniMax-M2.5',
      small_fast_model: 'Pro/MiniMaxAI/MiniMax-M2.5',
      provider: 'SiliconFlow',
      isPartner: true,
    },
    {
      id: 'siliconflow-en',
      name: 'SiliconFlow (EN)',
      category: 'aggregator',
      websiteUrl: 'https://siliconflow.com',
      apiKeyUrl: 'https://cloud.siliconflow.cn/i/drGuwc9k',
      base_url: 'https://api.siliconflow.com',
      model: 'MiniMaxAI/MiniMax-M2.5',
      small_fast_model: 'MiniMaxAI/MiniMax-M2.5',
      provider: 'SiliconFlow',
      isPartner: true,
    },
    {
      id: 'dmxapi',
      name: 'DMXAPI',
      category: 'aggregator',
      websiteUrl: 'https://www.dmxapi.cn',
      apiKeyUrl: 'https://www.dmxapi.cn',
      base_url: 'https://www.dmxapi.cn',
      provider: 'DMXAPI',
      isPartner: true,
    },
    {
      id: 'compshare',
      name: 'Compshare',
      category: 'aggregator',
      websiteUrl: 'https://www.compshare.cn',
      apiKeyUrl: 'https://www.compshare.cn/coding-plan?ytag=GPU_YY_YX_git_cc-switch',
      base_url: 'https://api.modelverse.cn',
      provider: 'Compshare',
      isPartner: true,
    },
    {
      id: 'openrouter',
      name: 'OpenRouter',
      category: 'aggregator',
      websiteUrl: 'https://openrouter.ai',
      apiKeyUrl: 'https://openrouter.ai/keys',
      base_url: 'https://openrouter.ai/api',
      model: 'anthropic/claude-sonnet-4.6',
      small_fast_model: 'anthropic/claude-haiku-4.5',
      provider: 'OpenRouter',
    },
    {
      id: 'novita',
      name: 'Novita AI',
      category: 'aggregator',
      websiteUrl: 'https://novita.ai',
      apiKeyUrl: 'https://novita.ai',
      base_url: 'https://api.novita.ai/anthropic',
      model: 'zai-org/glm-5',
      small_fast_model: 'zai-org/glm-5',
      provider: 'Novita AI',
    },
    {
      id: 'nvidia',
      name: 'Nvidia',
      category: 'aggregator',
      websiteUrl: 'https://build.nvidia.com',
      apiKeyUrl: 'https://build.nvidia.com/settings/api-keys',
      base_url: 'https://integrate.api.nvidia.com',
      model: 'moonshotai/kimi-k2.5',
      small_fast_model: 'moonshotai/kimi-k2.5',
      provider: 'Nvidia',
    },

    // ═══════════════════ third_party ═══════════════════
    {
      id: 'packycode',
      name: 'PackyCode',
      category: 'third_party',
      websiteUrl: 'https://www.packyapi.com',
      apiKeyUrl: 'https://www.packyapi.com/register?aff=cc-switch',
      base_url: 'https://www.packyapi.com',
      provider: 'PackyCode',
      isPartner: true,
    },
    {
      id: 'cubence',
      name: 'Cubence',
      category: 'third_party',
      websiteUrl: 'https://cubence.com',
      apiKeyUrl: 'https://cubence.com/signup?code=CCSWITCH&source=ccs',
      base_url: 'https://api.cubence.com',
      provider: 'Cubence',
      isPartner: true,
    },
    {
      id: 'aigocode',
      name: 'AIGoCode',
      category: 'third_party',
      websiteUrl: 'https://aigocode.com',
      apiKeyUrl: 'https://aigocode.com/invite/CC-SWITCH',
      base_url: 'https://api.aigocode.com',
      provider: 'AIGoCode',
      isPartner: true,
    },
    {
      id: 'rightcode',
      name: 'RightCode',
      category: 'third_party',
      websiteUrl: 'https://www.right.codes',
      apiKeyUrl: 'https://www.right.codes/register?aff=CCSWITCH',
      base_url: 'https://www.right.codes/claude',
      provider: 'RightCode',
      isPartner: true,
    },
    {
      id: 'aicodemirror',
      name: 'AICodeMirror',
      category: 'third_party',
      websiteUrl: 'https://www.aicodemirror.com',
      apiKeyUrl: 'https://www.aicodemirror.com/register?invitecode=9915W3',
      base_url: 'https://api.aicodemirror.com/api/claudecode',
      provider: 'AICodeMirror',
      isPartner: true,
    },
    {
      id: 'aicoding',
      name: 'AICoding',
      category: 'third_party',
      websiteUrl: 'https://aicoding.sh',
      apiKeyUrl: 'https://aicoding.sh/i/CCSWITCH',
      base_url: 'https://api.aicoding.sh',
      provider: 'AICoding',
      isPartner: true,
    },
    {
      id: 'crazyrouter',
      name: 'CrazyRouter',
      category: 'third_party',
      websiteUrl: 'https://www.crazyrouter.com',
      apiKeyUrl: 'https://www.crazyrouter.com/register?aff=OZcm&ref=cc-switch',
      base_url: 'https://crazyrouter.com',
      provider: 'CrazyRouter',
      isPartner: true,
    },
    {
      id: 'sssaicode',
      name: 'SSSAiCode',
      category: 'third_party',
      websiteUrl: 'https://www.sssaicode.com',
      apiKeyUrl: 'https://www.sssaicode.com/register?ref=DCP0SM',
      base_url: 'https://node-hk.sssaicode.com/api',
      provider: 'SSSAiCode',
      isPartner: true,
    },
    {
      id: 'micu',
      name: 'Micu',
      category: 'third_party',
      websiteUrl: 'https://www.openclaudecode.cn',
      apiKeyUrl: 'https://www.openclaudecode.cn/register?aff=aOYQ',
      base_url: 'https://www.openclaudecode.cn',
      provider: 'Micu',
      isPartner: true,
    },
    {
      id: 'x-code',
      name: 'X-Code API',
      category: 'third_party',
      websiteUrl: 'https://x-code.cc',
      apiKeyUrl: 'https://x-code.cc',
      base_url: 'https://x-code.cc',
      provider: 'X-Code',
      isPartner: true,
    },
    {
      id: 'ctok',
      name: 'CTok.ai',
      category: 'third_party',
      websiteUrl: 'https://ctok.ai',
      apiKeyUrl: 'https://ctok.ai',
      base_url: 'https://api.ctok.ai',
      provider: 'CTok.ai',
      isPartner: true,
    },
  ],
}
