#!/usr/bin/env python3
# 批量创建路由模块的脚本

import os

# 路由模块定义
ROUTE_MODULES = {
    "command_routes": [
        ("/api/command/execute", "post", "api::handlers::command::execute_command"),
        ("/api/command/execute/stream", "post", "api::handlers::command::execute_command_stream"),
        ("/api/command/list", "get", "api::handlers::command::list_commands"),
        ("/api/command/help/{command}", "get", "api::handlers::command::get_command_help"),
    ],
    "system_routes": [
        ("/api/system", "get", "api::handlers::system::get_system_info"),
    ],
    "version_routes": [
        ("/api/version", "get", "api::handlers::version::get_version"),
        ("/api/version/check-update", "get", "api::handlers::version::check_update"),
        ("/api/version/update", "post", "api::handlers::version::update_ccr"),
    ],
    "platform_routes": [
        ("/api/platforms", "get", "api::handlers::platform::list_platforms"),
        ("/api/platforms/current", "get", "api::handlers::platform::get_current_platform"),
        ("/api/platforms/switch", "post", "api::handlers::platform::switch_platform"),
        ("/api/platforms/{name}", "get", "api::handlers::platform::get_platform"),
        ("/api/platforms/{name}", "put", "api::handlers::platform::update_platform"),
        ("/api/platforms/{name}/enable", "post", "api::handlers::platform::enable_platform"),
        ("/api/platforms/{name}/disable", "post", "api::handlers::platform::disable_platform"),
        ("/api/platforms/{name}/profile", "get", "api::handlers::platform::get_platform_profile"),
        ("/api/platforms/{name}/profile", "post", "api::handlers::platform::set_platform_profile"),
    ],
}

def create_route_file(module_name, routes):
    """创建路由模块文件"""
    content = f'''// {module_name.replace('_', ' ').title()} routes
// Generated by create_routes.py

use axum::{{
    routing::{delete, get, patch, post, put},
    Router,
}};

/// {module_name.replace('_', ' ').title()}
pub fn routes() -> Router {{
    Router::new()'''

    for path, method, handler in routes:
        content += f'''
        .route("{path}", {method}({handler}))'''

    content += '''
}

pub fn main():
    """创建所有路由模块"""
    base_path = "/home/lyh/Documents/Github/ccr/ccr-ui/backend/src/routes"

    for module_name, routes in ROUTE_MODULES.items():
        file_path = f"{base_path}/{module_name}.rs"
        with open(file_path, 'w') as f:
            f.write(create_route_file(module_name, routes))
        print(f"Created {file_path}")

if __name__ == "__main__":
    main()