//! 15 分类静态定义。移植 skill-hub `server/scanner/taxonomy.ts::CATEGORIES`。

/// 兜底分类 id。
pub const CATEGORY_OTHER: &str = "other";

/// 分类定义。
pub struct CategoryDef {
    pub id: &'static str,
    pub name_en: &'static str,
    pub name_zh: &'static str,
    pub icon: &'static str,
    pub keywords: &'static [&'static str],
    /// 平分时优先级更高的胜出。
    pub priority: u32,
}

/// 15 个分类 — 按常见度排序。`other` 必须最后，其 keywords 为空永不命中 keyword 分支。
pub const CATEGORIES: &[CategoryDef] = &[
    CategoryDef {
        id: "code-dev",
        name_en: "Code Development",
        name_zh: "代码开发",
        icon: "💻",
        keywords: &[
            "tdd",
            "frontend",
            "backend",
            "api",
            "debug",
            "refactor",
            "lint",
            "ci",
            "git",
            "commit",
            "pull-request",
            "review",
            "typescript",
            "python",
            "rust",
            "golang",
            "java",
            "react",
            "vue",
            "next",
            "webpack",
            "vite",
            "npm",
            "pnpm",
            "bun",
            "deno",
        ],
        priority: 5,
    },
    CategoryDef {
        id: "content",
        name_en: "Content Creation",
        name_zh: "内容创作",
        icon: "✍️",
        keywords: &[
            "write",
            "article",
            "blog",
            "copywriting",
            "seo",
            "newsletter",
            "文章",
            "写作",
            "创作",
            "选题",
            "大纲",
            "稿件",
            "essay",
        ],
        priority: 5,
    },
    CategoryDef {
        id: "image-gen",
        name_en: "Image Generation",
        name_zh: "图片生成",
        icon: "🎨",
        keywords: &[
            "image",
            "picture",
            "photo",
            "cover",
            "banner",
            "illustration",
            "封面",
            "配图",
            "插画",
            "dalle",
            "midjourney",
            "flux",
            "stable-diffusion",
            "comfyui",
            "logo",
        ],
        priority: 6,
    },
    CategoryDef {
        id: "video-audio",
        name_en: "Video & Audio",
        name_zh: "视频/音频",
        icon: "🎬",
        keywords: &[
            "video", "audio", "ffmpeg", "remotion", "mp4", "podcast", "subtitle", "srt", "tts",
            "voice", "视频", "音频", "字幕",
        ],
        priority: 5,
    },
    CategoryDef {
        id: "data",
        name_en: "Data Analysis",
        name_zh: "数据分析",
        icon: "📊",
        keywords: &[
            "data",
            "analytics",
            "chart",
            "csv",
            "excel",
            "dashboard",
            "visualization",
            "stats",
            "metrics",
            "sql",
            "database",
            "报告",
            "报表",
            "统计",
        ],
        priority: 5,
    },
    CategoryDef {
        id: "web-search",
        name_en: "Web Search",
        name_zh: "网络搜索",
        icon: "🔍",
        keywords: &[
            "search",
            "web",
            "browse",
            "scrape",
            "crawl",
            "spider",
            "搜索",
            "抓取",
            "爬虫",
            "google",
            "bing",
            "perplexity",
        ],
        priority: 6,
    },
    CategoryDef {
        id: "social",
        name_en: "Social Media",
        name_zh: "社交媒体",
        icon: "📱",
        keywords: &[
            "小红书",
            "xhs",
            "twitter",
            "weibo",
            "公众号",
            "wechat",
            "instagram",
            "tiktok",
            "抖音",
            "微博",
            "linkedin",
            "threads",
            "youtube",
            "bilibili",
            "x.com",
        ],
        priority: 7,
    },
    CategoryDef {
        id: "doc",
        name_en: "Document",
        name_zh: "文档处理",
        icon: "📄",
        keywords: &[
            "pdf",
            "docx",
            "pptx",
            "xlsx",
            "notion",
            "confluence",
            "文档",
            "readme",
            "spec",
            "rfc",
            "wiki",
        ],
        priority: 5,
    },
    CategoryDef {
        id: "comms",
        name_en: "Communication",
        name_zh: "通讯协作",
        icon: "💬",
        keywords: &[
            "email", "mail", "slack", "feishu", "lark", "dingtalk", "telegram", "discord", "飞书",
            "邮件", "钉钉", "teams",
        ],
        priority: 5,
    },
    CategoryDef {
        id: "design",
        name_en: "Design / UI",
        name_zh: "设计/UI",
        icon: "🖌️",
        keywords: &[
            "figma",
            "ui",
            "ux",
            "canvas",
            "theme",
            "brand",
            "sketch",
            "wireframe",
            "prototype",
            "tailwind",
            "css",
            "设计",
        ],
        priority: 5,
    },
    CategoryDef {
        id: "translate",
        name_en: "Translate / i18n",
        name_zh: "翻译/i18n",
        icon: "🌐",
        keywords: &[
            "translate",
            "translation",
            "i18n",
            "l10n",
            "locale",
            "翻译",
            "多语言",
            "本地化",
        ],
        priority: 6,
    },
    CategoryDef {
        id: "sysadmin",
        name_en: "System Admin",
        name_zh: "系统管理",
        icon: "🖥️",
        keywords: &[
            "server",
            "docker",
            "k8s",
            "kubernetes",
            "devops",
            "ssh",
            "linux",
            "nginx",
            "infra",
            "terraform",
            "aws",
            "gcp",
            "azure",
            "运维",
            "部署",
            "monitor",
        ],
        priority: 5,
    },
    CategoryDef {
        id: "persona",
        name_en: "Persona",
        name_zh: "人格/角色",
        icon: "🎭",
        keywords: &[
            "personality",
            "persona",
            "mbti",
            "sbti",
            "character",
            "role",
            "人格",
            "角色",
            "蒸馏",
            "roleplay",
            "assistant",
        ],
        priority: 6,
    },
    CategoryDef {
        id: "finance",
        name_en: "Finance",
        name_zh: "财务/金融",
        icon: "💰",
        keywords: &[
            "finance",
            "invoice",
            "receipt",
            "stock",
            "trade",
            "accounting",
            "发票",
            "财务",
            "金融",
            "投资",
            "报销",
            "budget",
        ],
        priority: 5,
    },
    // 兜底 — 必须最后；keywords 为空，仅在其他全不命中时被 classify 选中
    CategoryDef {
        id: CATEGORY_OTHER,
        name_en: "Other",
        name_zh: "其他",
        icon: "📦",
        keywords: &[],
        priority: 0,
    },
];

/// 按 id 查找分类。
pub fn category_by_id(id: &str) -> Option<&'static CategoryDef> {
    CATEGORIES.iter().find(|c| c.id == id)
}
