# CCR WebDAV 同步配置示例
# 此文件展示如何配置 WebDAV 云端同步功能

# 全局设置
[settings]
# 自动确认模式（跳过确认提示）
skip_confirmation = false

# WebDAV 同步配置（可选）
[settings.sync]
# 启用同步功能
enabled = true

# WebDAV 服务器地址
# 坚果云（默认）: https://dav.jianguoyun.com/dav/
# Nextcloud: https://your-server.com/remote.php/dav/files/username/
# ownCloud: https://your-server.com/remote.php/webdav/
webdav_url = "https://dav.jianguoyun.com/dav/"

# 用户名（坚果云使用邮箱）
username = "your-email@example.com"

# 密码/应用密码
# ⚠️ 坚果云用户请使用应用密码，而非账户密码
# 获取方式：账户信息 -> 安全选项 -> 添加应用 -> 生成密码
password = "your_app_password_here"

# 远程文件路径（配置文件在 WebDAV 服务器上的路径）
# 建议使用专门的目录，避免与其他文件混淆
remote_path = "/ccr/.ccs_config.toml"

# 自动同步模式（预留字段，暂未实现）
# 启用后，每次配置操作后自动同步到云端
auto_sync = false

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 其他配置节示例
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

default_config = "anthropic"
current_config = "anthropic"

[anthropic]
description = "Anthropic 官方 API"
base_url = "https://api.anthropic.com"
auth_token = "sk-ant-xxxxx"
model = "claude-3-5-sonnet-20241022"
small_fast_model = "claude-3-5-haiku-20241022"

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 💡 使用提示
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# 1. 快速开始
#    ccr sync config          # 交互式配置同步
#    ccr sync status          # 查看同步状态
#    ccr sync push            # 上传配置到云端
#    ccr sync pull            # 从云端下载配置

# 2. 坚果云配置
#    - 服务器地址：https://dav.jianguoyun.com/dav/
#    - 用户名：您的坚果云邮箱
#    - 密码：应用密码（非账户密码）
#    - 应用密码获取：登录网页版 -> 账户信息 -> 安全选项 -> 添加应用

# 3. 其他 WebDAV 服务
#    修改 webdav_url 为对应服务的 WebDAV 地址即可
#    常见服务：
#    - Nextcloud: https://your-server.com/remote.php/dav/files/username/
#    - ownCloud: https://your-server.com/remote.php/webdav/
#    - Box.com: https://dav.box.com/dav/
#    - pCloud: https://webdav.pcloud.com/

# 4. 安全建议
#    - 使用应用专用密码，避免使用主账户密码
#    - 不要将此配置文件提交到公开仓库
#    - 定期更换密码
#    - 使用 HTTPS 确保传输安全

# 5. 多设备同步
#    设备 A（主设备）：
#      ccr sync config        # 配置同步
#      ccr sync push          # 首次上传
#
#    设备 B：
#      ccr sync config        # 使用相同配置
#      ccr sync pull          # 下载配置

# 6. 故障排除
#    - 认证失败：检查用户名和密码（坚果云需使用应用密码）
#    - 网络错误：检查服务器地址和网络连接
#    - 文件不存在：首次使用需先 push 上传配置
